version: "3"

services:
  redis:
    image: redis
    container_name: ms-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - funeraria-network

networks:
  funeraria-network:
    external:
      name: funeraria-network

