version: "3"

services:
  redis:
    image: redis
    container_name: redis
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: always
    networks:
      - funeraria-network

networks:
  funeraria-network:
    name: funeraria-network

